services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_POrT}:${DB_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: my_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: ["npm", "run", "dev"]