services:
  montorae-api:
    image: mentorae-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3010:3010"
    depends_on:
      - db
    
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackathon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
